"""add active user unique indexes

Revision ID: 15aa3619b032
Revises: 4f6a8b0c2d3e
Create Date: 2026-09-12 16:44:08.548075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15aa3619b032'
down_revision: Union[str, Sequence[str], None] = '4f6a8b0c2d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('app_users_email_key'), 'app_users', type_='unique')
    op.drop_constraint(op.f('app_users_username_normalized_key'), 'app_users', type_='unique')
    op.create_index('uq_app_users_active_email', 'app_users', ['email'], unique=True, postgresql_where=sa.text('is_active = TRUE'))
    op.create_index('uq_app_users_active_username', 'app_users', ['username_normalized'], unique=True, postgresql_where=sa.text('is_active = TRUE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_app_users_active_username', table_name='app_users', postgresql_where=sa.text('is_active = TRUE'))
    op.drop_index('uq_app_users_active_email', table_name='app_users', postgresql_where=sa.text('is_active = TRUE'))
    op.create_unique_constraint(op.f('app_users_username_normalized_key'), 'app_users', ['username_normalized'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('app_users_email_key'), 'app_users', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
