"""empty message

Revision ID: 69b849fd1043
Revises: 83e5ec226cc6
Create Date: 2026-05-28 17:37:24.436178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69b849fd1043'
down_revision: Union[str, Sequence[str], None] = '83e5ec226cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_task_team_status_position', 'tasks', ['team_id', 'status', 'position'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_task_team_status_position', 'tasks', type_='unique')
    # ### end Alembic commands ###
