"""initial migration

Revision ID: 83e5ec226cc6
Revises: 
Create Date: 2026-05-10 10:08:48.925796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from backend.app.models.enums import IntEnumType, TaskEffort

# revision identifiers, used by Alembic.
revision: str = '83e5ec226cc6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('id', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('organization_name', sa.String(length=200), nullable=False),
    sa.Column('initialized_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('in_progress_limit', sa.Integer(), server_default=sa.text('2'), nullable=False),
    sa.CheckConstraint("btrim(organization_name) <> ''", name='app_config_name_not_blank'),
    sa.CheckConstraint('id = 1', name='app_config_singleton'),
    sa.CheckConstraint('in_progress_limit > 0', name='app_config_in_progress_limit'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('username_normalized', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('profile_picture_path', sa.Text(), nullable=True),
    sa.Column('last_active_team_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("btrim(email) <> ''", name='user_email_not_blank'),
    sa.CheckConstraint("btrim(password_hash) <> ''", name='user_password_hash_not_blank'),
    sa.CheckConstraint("btrim(username) <> ''", name='user_username_not_blank'),
    sa.CheckConstraint("btrim(username_normalized) <> ''", name='user_username_normalized_not_blank'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username_normalized')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('private', 'team', name='team_type'), server_default=sa.text("'team'"), nullable=False),
    sa.Column('private_owner_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.CheckConstraint("btrim(name) <> ''", name='team_name_not_blank'),
    sa.CheckConstraint('("type" = \'private\' AND private_owner_user_id IS NOT NULL) OR ("type" = \'team\' AND private_owner_user_id IS NULL)', name='team_type_owner_consistency'),
    sa.ForeignKeyConstraint(['private_owner_user_id'], ['app_users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('private_owner_user_id', name='uq_team_private_owner')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_token_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("btrim(session_token_hash) <> ''", name='session_token_hash_not_blank'),
    sa.CheckConstraint('expires_at > created_at', name='check_expires_at'),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token_hash')
    )
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', 'contractor', 'guest', name='team_member_role'), server_default=sa.text("'member'"), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_member_team_user')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('creator_member_id', sa.Integer(), nullable=False),
    sa.Column('assignee_member_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_member_id', sa.Integer(), nullable=True),
    sa.Column('layer', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('todo', 'in_progress', 'review', 'done', name='task_status'), server_default=sa.text("'todo'"), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='task_priority'), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('effort', IntEnumType(TaskEffort), nullable=True),
    sa.Column('should_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_working_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_for_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('returned_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('reopened_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('blocked_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint("(status = 'done' AND completed_at IS NOT NULL) OR (status <> 'done' AND completed_at IS NULL)", name='task_completed_at_matches_status'),
    sa.CheckConstraint("(submitted_for_review_at IS NULL) OR (status IN ('review', 'done'))", name='task_review_timestamp_only_after_review'),
    sa.CheckConstraint("btrim(title) <> ''", name='task_title_not_blank'),
    sa.CheckConstraint("layer IS NULL OR btrim(layer) <> ''", name='task_layer_not_blank'),
    sa.CheckConstraint('(should_review = TRUE AND reviewer_member_id IS NOT NULL)OR(should_review = FALSE AND reviewer_member_id IS NULL)', name='should_review_must_have_reviewer'),
    sa.CheckConstraint('blocked_count >= 0', name='task_blocked_count_non_negative'),
    sa.CheckConstraint('position >= 1', name='task_position'),
    sa.CheckConstraint('reopened_count >= 0', name='task_reopened_count_non_negative'),
    sa.CheckConstraint('returned_count >= 0', name='task_returned_count_non_negative'),
    sa.ForeignKeyConstraint(['assignee_member_id'], ['team_members.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['creator_member_id'], ['team_members.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewer_member_id'], ['team_members.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('team_members')
    op.drop_table('user_sessions')
    op.drop_table('teams')
    op.drop_table('app_users')
    op.drop_table('app_config')
    # ### end Alembic commands ###
